### ISSUE TITLE
Rolls and bust

### ISSUE THREAD

**Issue by Kenshikaze** [DanielHazzard/FFXI-RollBot#2]
So first time using the rollbot. Did Corsair roll and a couple double ups followed by snake eyes ended up with 10. Waited about 15seconds (I thought for PR cd so can do roll 2) Then used double up again and busted. Used fold, spammed cor roll again til it got 7. Won't use second roll.

**Comment by DanielHazzard** [comment]
Can you confirm that it's showing the correct roll number next to 

Current Roll: (0-12)

**Comment by DanielHazzard** [comment]
I've pushed a new version RC6, can you try that version, you need to replace the addon as well with the one in the ZIP.

**Comment by DanielHazzard** [comment]
I've pushed a new release, this uses the same method I use in CurePlease so it sends the roll data via local internet as such you'll need to accept the Firewall notice. 

There seems to be a flaw with EliteAPI's command reading for some people which is causing it to not be read correctly.
